### ISSUE TITLE
Image storage on backend

### ISSUE THREAD

**Issue by Pipazoul** [datatlas-erasme/front#40]
**Is your feature request related to a problem? Please describe.**
When creating a new instance the instance logo is not fetched from the api

**Describe the solution you'd like**
Having a API route where i could upload images

**Comment by racine-p-a** [comment]
What is this picture ?
And where is it ? On our server or outside ?

**Comment by Pipazoul** [comment]
The logo pictures specific to an instance, for the **industrie** instance this will not be fixed for now, and will still be hardcoded, but on the future instances, it would be possible to upload and modify (on our server => on the backend) logos (and whatever static media needed)  displayed on the front

**Comment by racine-p-a** [comment]
Our goal : 
- creation of a `/upload` route to store files on the backend
- those files will always be stored inside the same folder
- the front can call the uri : `backend/folder/filename`

**Comment by racine-p-a** [comment]
@Pipazoul same answer/work as in https://github.com/datatlas-erasme/front/issues/41 ?

**Comment by Pipazoul** [comment]
`node:internal/validators:120
back-datatlas-back-1  |     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
back-datatlas-back-1  |     ^
back-datatlas-back-1  |
back-datatlas-back-1  | TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
back-datatlas-back-1  |     at new NodeError (node:internal/errors:372:5)
back-datatlas-back-1  |     at validateString (node:internal/validators:120:11)
back-datatlas-back-1  |     at Object.join (node:path:1172:7)
back-datatlas-back-1  |     at /src/server.js:114:37
back-datatlas-back-1  |     at IncomingForm.<anonymous> (/src/node_modules/formidable/lib/incoming_form.js:107:9)
back-datatlas-back-1  |     at IncomingForm.emit (node:events:527:28)
back-datatlas-back-1  |     at IncomingForm._maybeEnd (/src/node_modules/formidable/lib/incoming_form.js:563:8)
back-datatlas-back-1  |     at /src/node_modules/formidable/lib/incoming_form.js:242:12
back-datatlas-back-1  |     at Array.<anonymous> (/src/node_modules/formidable/lib/file.js:79:5)
back-datatlas-back-1  |     at finish (node:internal/streams/writable:752:25) {
back-datatlas-back-1  |   code: 'ERR_INVALID_ARG_TYPE'
back-datatlas-back-1  | }
back-datatlas-back-1  |
back-datatlas-back-1  | Node.js v17.9.0`

**Comment by racine-p-a** [comment]
@Pipazoul I am unable to reproduce this bug. Do you get it from Postman or your own uploads from the front ?
